spring:
  cloud:
    gateway:
      routes:
        - id: servicio-productos
          uri: http://localhost:8081
          predicates:
            - Path=/productos/**
        - id: servicio-precios
          uri: http://localhost:8082
          predicates:
            - Path=/precios/**
        - id: servicio-notificaciones
          uri: http://localhost:8083
          predicates:
            - Path=/notificaciones/**